### ISSUE TITLE
ja: Make docs/setup/release/version-skew-policy.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26527]
**This is a Feature Request**

**What would you like to be added**
Update docs/setup/release/version-skew-policy.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/setup/release/version-skew-policy.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.18-ja.2/content/ja/docs/setup/release/version-skew-policy.md

Original
https://github.com/kubernetes/website/tree/release-1.18/content/en/docs/setup/release/version-skew-policy.md

diff between translated and v1.18
https://gist.github.com/ac467795dacb7d76a5175d9d2e93a392

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by task4233** [comment]
I'm afraid that it seems this PR has already been resolved in #25268.
I'm sorry if that is wrong.

**Comment by inductor** [comment]
Hello. thank you for your contribution!
The original issue is still under evaluation by other reviewers as it has `needs-triage` label. Thank you for pointing it out!

**Comment by task4233** [comment]
I appreciate your advice,
I did not understand the meaning of the `needs-triage` label.
I will wait until its label is removed.

**Comment by nasa9084** [comment]
@task4233 さんの言うように、もう解決済みっぽい感じがしますね
