### ISSUE TITLE
storageclass.storage.k8s.io "manual" not found

### ISSUE THREAD

**Issue by winkee01** [kubernetes/website#30912]
##### Environment:
Kube cluster is running on local Lan.

##### Symptom
So I followed with [the official tutorial](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/) about creating a PVC, but after I created PV and PVC,  I got this error saying `"manual" not found`. 

On that page it defines a StorageClass in PV's config file (listed below), I think this might be very confusing because there is no information about where this **`manual`** StorageClass comes from, is it a StorageClass already defined somewhere?, or we just declare a new one here. 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

The error clearly says "manual" StorageClass is not found, when I query `kubectl get storageclass`, it says No resources found. 

Can you make "manual" here more sense? 

##### Another observation
After I delete PV and PVC, and recreate them, the error disappears, wow, I am even more confused.

**Comment by sftim** [comment]
/sig storage
/remove-kind support
/kind bug
/language en

Thanks for reporting this @winkee01 

I think that page is out of date and does need fixing.

**Comment by sftim** [comment]
/retitle Error following “Configure a Pod to Use a PersistentVolume for Storage”: storageclass.storage.k8s.io "manual" not found

**Comment by Kartik494** [comment]
Hi @winkee01 ,
 
> ##### Another observation
> After I delete PV and PVC, and recreate them, the error disappears, wow, I am even more confused.

In my env i got the same error after recreating the pv and pvc . PV and PVC get created while i use a different name only even i don't have that SC in my env. I am looking into it. why it's this so.
Thanks

**Comment by Kartik494** [comment]
@sftim  for more clarification on this is this a good idea to add a note for  `SC ` ?

**Comment by sftim** [comment]
@Kartik494 perhaps you could explain your question more?

The page at https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/ is out of date, and we need to fix it. Someone can check that it is fixed by performing the task and observing that you can complete it without any issue.

**Comment by Kartik494** [comment]
@sftim For new users it might seems confusing from where they are getting storage class named `manual`, i think we should add a note for clarification , but not sure on this

**Comment by quynhdang-vt** [comment]
> Hi @winkee01 ,
> 
> > ##### Another observation
> > After I delete PV and PVC, and recreate them, the error disappears, wow, I am even more confused.
> 
> In my env i got the same error after recreating the pv and pvc . PV and PVC get created while i use a different name only even i don't have that SC in my env. I am looking into it. why it's this so. Thanks

SO did I -- deleting, uninstall, reinstall, redeployment still show the same error.

**Comment by winkee01** [comment]
> Hi @winkee01 ,
> 
> > ##### Another observation
> > After I delete PV and PVC, and recreate them, the error disappears, wow, I am even more confused.
> 
> In my env i got the same error after recreating the pv and pvc . PV and PVC get created while i use a different name only even i don't have that SC in my env. I am looking into it. why it's this so. Thanks

I tried to delete PV & PVC, but unfortunately, I can create PV & PVC without error, thus not being able to recreate your errors. I don't know why. So, to my understanding at this point, if you specify a non-exist SC in PV, it virtually defines it, and you can specify it in PVC so that they can be bound. But I have no idea why the error says "manual not found". Very misleading and confusing error information.

**Comment by sftim** [comment]
When a page has a prerequisite, we should document it. For this task, I recommend that we cover how to set up any StorageClass that the task requires. The exception would be if we can direct readers to a different task and recommend that they follow the other task page first.

/triage accepted

**Comment by Kartik494** [comment]
@sftim Adding a page reference for how to create a storage class first is good direction to proceed?

**Comment by Kartik494** [comment]
> When a page has a prerequisite, we should document it. For this task, I recommend that we cover how to set up any StorageClass that the task requires. The exception would be if we can direct readers to a different task and recommend that they follow the other task page first.

I think there is already mentioning of creating a storage class in [doc](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume) before creating PV.

**Comment by os6sense** [comment]
I'm also affected by this issue when trying to setup a hostpath based pv for local development. Actually understanding the problem is hard enough because this is the first hit on google and to my mind, no one has actually answered the original question.

My understand so far is that there isn't actually a StorageClass named "manual", rather the hostpath based PV is provisioned statically and "manual" is used purely for naming purposes. Is this correct? 

One reason I've identified for this error is that if any other accessMode apart from ReadWriteOnce is used (which I know isn't valid but I recently did by mistake), any PVC using this will be stuck in the pending state with this as a somewhat misleading error. Sadly, this also seems to happen at random when tearing down and setting up the PV/PVCs ...

**Comment by Eternal21** [comment]
I was also following the linked tutorial, and hit the same error.  After reading this thread, I am still not clear on how to proceed.

**Comment by allaismail** [comment]
i have the same error 
storageclass.storage.k8s.io "manual" not found   
what is the solution ?

**Comment by sftim** [comment]
For this task, I recommend that we cover how to set up any StorageClass that the task requires. The exception would be if we can direct readers to a different task and recommend that they follow the other task page first.

The Kubernetes project can help people here by adding more explanation to the existing web page. This is similar to the point in
https://github.com/kubernetes/website/issues/30912#issuecomment-1031395765

**Comment by os6sense** [comment]
The problem isn't necessarily one of setting up the StorageClass though, it's that **if the PVC cannot bind to the hostpath PV for ANY reason** the error is a very generic and misleading one of `storageclass.storage.k8s.io "manual" not found`.

In the case of @winkee01 if sounds like repetition of the tutorial failed _probably_ because the PV was already bound. Possibly the best solution is to add a warning that before attempting the steps again the `Clean up` instructions should be followed.

**Comment by matthiasdg** [comment]
I also came here after following the example at kubernetes.io linked above. I did not encounter errors, but was surprised that when I listed my storageclasses using k9s no "manual" was found. It's pretty hilarious that there is still no explanation on this issue.
Based on  https://www.kubermatic.com/blog/keeping-the-state-of-apps-4-persistentvolumes-and-persistentvolum/ and https://www.kubermatic.com/blog/keeping-the-state-of-apps-5-introduction-to-storage-classes/, are these only required for dynamic provisioning and can I use whatever I want for manual PVs (such as hostPath) as long as the two match?

**Comment by m-brando** [comment]
by default, if you don't define StorageClass (SC) in your PersistentVolumeClaims (PVC) the PVC will use the default SC called standard https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass. 

This default SC is then used to dynamically provision storage for PVC that does not require any specific storage class https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/#why-change-the-default-storage-class

To my understanding, if you define `storageClassName: manual ` in spec of yaml file for persistent volume, it also needs to be defined for PVC.  This SC `manual` won't get created and is used to bind persistent volume claim requests to this persistent volume.

**Comment by mehboobpatel** [comment]
> /sig storage /remove-kind support /kind bug /language en
> 
> Thanks for reporting this @winkee01
> 
> I think that page is out of date and does need fixing.

Hey Tim can we please connect on linkedin or via mail  i am facing the same issue in  performing task https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by dickieku** [comment]
use `storageClassName: ""` will fix

**Comment by werniq** [comment]
How I solved it:

Try to get all storageclasses, if nothing shows up - create one (there should be one be default tho)
If there is at least 1 result, use it in your pvc

**Comment by yashaswi-nayak** [comment]
I tried the example, a small change is required for the local type volumes.
Use `standard` instead of `manual` for storageClassName.
Here's my example

File - `pv-volume.yaml`

    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: k8-pv-volume
      labels:
        type: local
    spec:
      storageClassName: standard
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        path: "/tmp/data"

File - `pv-claim.yaml`

    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: k8-pv-claim
      namespace: default
    spec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
