### ISSUE TITLE
Document kubectl config file format

### ISSUE THREAD

**Issue by mleonhard** [kubernetes/website#38478]
**What would you like to be added**:

Documentation of `kubectl` YAML config files

**Why is this needed**:

So I can understand, write, and maintain kubectl config files.

**Expressing frustration**:

I'm learning Kubernetes.  I went through the tutorials - thanks.  Now I'm trying to set up services to run on minikube and my hosting provider.  The kubectl command apparently takes a YAML config file.  I searched for 15 mins and **found no documentation for it at all**.  I found a helpful [blog post complaining about the missing documentation](https://vsupalov.com/yaml-kubernetes-examples-docs-spec/).  There are examples: [guestbook-all-in-one.yaml](https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml), [a deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment), [a service](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service), [a replica set](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#example), and [a replication controller](
https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#running-an-example-replicationcontroller).  The "Getting Start / Production Environment" documentation contains no guidance on using config files to define application deployments.

Should I deploy my code with bash scripts that call `kubectl create deployment ...` ?  Is that how Google engineers work?  No, they write borgcfg files.  And they learned how to write borgcfg by reading the borgcfg docs.  There's even a codelab (tutorial) on writing such files.  Imagine trying to onboard new Googler SWEs without letting them read the borgcfg documentation or teaching them how to write borgcfg files.  Nobody would do that.  Yet Google wants us to use Kubernetes, to deploy on Google Cloud, and doesn't provide this basic doc.

The kubectl config file is crucial information that *everyone* learning Kubernetes must learn.  Please don't make us hunt for this information, guess at the meanings of examples, and read unreliable Stack Overflow answers and blog posts.  Just provide usable documentation.  Please?

**Comment by sftim** [comment]
- https://kubernetes.io/docs/reference/config-api/ doesn't yet mention `kubectl`.
- https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#what-s-next has no link to learn about the format

**Comment by tengqm** [comment]
There is nothing like a config API for this purpose. The website has some useful information here: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

The page could use some improvement because `kubeconfig` file is not just for accessing multiple clusters.

**Comment by sftim** [comment]
I'd like to add a reference that is similar to the pages within https://kubernetes.io/docs/reference/config-api/
I can make a quick mockup (if that'd help?)

We don't need to generate the new page automatically. It _is_ useful if the references are consistent, though.

**Comment by sftim** [comment]
Done: https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/

/close

**Comment by mleonhard** [comment]
Thanks for adding docs about how to configure kubectl command auth to k8s clusters.Is there also documentation for defining pods, servers, ingress, and data storage? I still can’t find it. That’s what new k8s users need.. That’s what this ticket is about.Please re-open./open/reopen/re-open

**Comment by sftim** [comment]
@mleonhard _this_ issue is resolved.

If you would like to request further improvements, you are welcome to file further issues. It's best to use a new issue for each logically separate improvement.
If you are considering making a suggestion, please check to see whether it has already been requested; if so, you could upvote the existing issue.

I recommend that you read [tips for writing a good issue](https://dev.to/orliesaurus/writing-great-tickets-in-open-source-projects-1kj8#tips-for-writing-a-good-issue); even if you have already read a similar guide, it's worth having a fresh idea of how open source projects encourage contributors to act.

**Comment by mleonhard** [comment]
@sftim You linked to docs that are different than what this ticket asked for.  The sidebar is not visible at all on mobile, making it hard to find the needed docs.  On desktop, I was able to find them: https://kubernetes.io/docs/reference/kubernetes-api/ .  Thank you!  

There is still a lot of room for improvement.  This ticket is about docs for new users, specifically how to set up services to run in a k8s cluster.  The docs now have that info, but put it under "Kubernetes API".  I've been doing software for 15 years, including stints at AWS and Google infrastructure.  To me, "Kubernetes API" is the RPC interface for controlling a Kubernetes cluster.  I would read that when I work on Kubernetes management tools.

But I just want to make my server run on a Kubernetes cluster, using existing tools.  **I just need to know what to put in the @#%$@ config file.**  That's what this ticket is about.

So all new Kubernetes users must first learn that the info about "what to put in the config file" is under "Kubernetes API".  Finding that info will take time.  This is time that most new users will waste.  Please fix this.  And next time you write or change documentation or user interfaces, please try harder to consider the needs of the users.
