### ISSUE TITLE
Stale "Twitter" icon and name (s) - should now be "X" corp.

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43206]
**This is a Feature Request**

**What would you like to be added/enhanced?**
As everybody knows, Twitter is now under X corp. and its world famous blue bird icon has been changed to "X" icon a long time ago. So, maybe we should update it here in footer too.

**Why is this needed?**
I know everyone likes that blue twitter icon, and twitter is better recognised with that icon. But as company has been renamed to "X" with "X" icon then shouldn't we update it?

**Comment by sftim** [comment]
/kind bug
(the website is “wrong” now)

/priority backlog

Contributors: **please feel free to work on other issues; this one isn't a priority.**

/retitle Stale "Twitter" icon and name (s) - should now be "X" corp.

We use the Twitter logo and brand on https://kubernetes.io/community/ too

**Comment by Gauravpadam** [comment]
I'll look into this after other issues ; Meanwhile anyone can propose a fix

**Comment by aj11anuj** [comment]
😅 I think it's priority backlog, but it's also reserved to be resolved in-future. 

Currently, i guess no one is in favour to change it, but it will be updated in-future after several months.

**Comment by pranshugupta01** [comment]
hi can i work on this issue?

**Comment by Gauravpadam** [comment]
Sure @pranshugupta01, Go ahead

**Comment by sftim** [comment]
Help is welcome. However, the Kubernetes project is not a participant in Hacktoberfest.

You can read https://hacktoberfest.com/participation/ to learn more.

**Comment by pedoch** [comment]
@sftim thank you, I realise that now. 

I attempted working on the issue regardless. Looks like it'll required upgrading the fontawesome, but I honestly can't figure out how to do that. Fontawesome seems to be coming docusy? 

Unfortunately, doesn't look I'd be of much help.

**Comment by chansuke** [comment]
@Gauravpadam I'd like to work on this.

**Comment by Gauravpadam** [comment]
> @Gauravpadam I'd like to work on this.

Sure, Please go ahead

**Comment by rohan-kapse** [comment]
@chansuke could u describe your approach plzz ?

**Comment by Manish-hr14** [comment]
can i work on this issue??

**Comment by Rajdeep1311** [comment]
@Gauravpadam are you still working?

**Comment by Gauravpadam** [comment]
@Rajdeep1311 Please go ahead and propose a fix

**Comment by Manish-hr14** [comment]
issue has been solved already.

**Comment by Rajdeep1311** [comment]
But I see PR was merged and again opened

**Comment by Gauravpadam** [comment]
The footer still shows the "old" logo — shouldn't we update that too?

A docsy theme update might be necessary for this
