### ISSUE TITLE
Website search function is broken

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/website#6158]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
The website search function does not return results. When I search for "Pod" the following happens:
![screen shot 2017-11-02 at 11 31 33 am](https://user-images.githubusercontent.com/13116240/32343731-bf43b4ce-bfc1-11e7-91c2-a322a19309d6.png)

**Proposed Solution:**
Fix the search function to find and/or display results

**Page to Update:**
http://kubernetes.io/docs/search

**Comment by zacharysarah** [comment]
@guineveresaenger 👋 Thanks for opening this. We're aware of it and looking for what went wrong.

**Comment by abiogenesis-now** [comment]
Fixed, this was caused by a bad PR on my part. I reverted it, search should be working again.

**Comment by Bregor** [comment]
Still broken :(

![search results - kubernetes 2017-11-03 10-17-19](https://user-images.githubusercontent.com/745/32363400-467ab6c2-c080-11e7-9cb7-209c74bb8d44.png)

**Comment by zacharysarah** [comment]
@Bregor Function looks normal to me. Refresh and try again?

**Comment by guineveresaenger** [comment]
Can confirm that it works for me. Thank you!

**Comment by Bregor** [comment]
Yep, works now. 
Sorry for buzzing
