### ISSUE TITLE
Hugo website - Service catalog missing and not translated

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8275]
This issue is to track that the service catalog page shows up in the TOC and that it renders correctly.

https://k8sio-hugo-migration.netlify.com/docs/concepts/service-catalog/

- [ ] Feature Request
- [X] Bug Report

- The page is missing from the TOC under Extending Kubernetes
- The page is not rendering correctly, it looks like it was written in HTML

**Comment by bep** [comment]
This is the "prepend text" logic in the glossary_definition shortcode. I will fix.

**Comment by bep** [comment]
This is fixed.

**Comment by clintkitson** [comment]
I see that the page renders correctly now, but it looks like Extending Kubernetes item is still missing from the TOC so I can't verify this.
